/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs");
const port = 3000;
const fileDB =
  "C:/Workspaces/Vscode_workspaces/Full_Stack_Course/Week-2-Assignments/02-nodejs/fileDB.json";

const app = express();
app.listen(port, () => console.log("App Started, listing on 3000 !!"));
app.use(bodyParser.json());

app.post("/todos", (req, res) => {
  let dataArray = [];
  const existingData = fs.readFileSync(fileDB, "utf8");
  if (existingData !== "") {
    dataArray = JSON.parse(existingData);
  }
  const reqBody = req.body;
  console.log(reqBody);
  const id = Math.floor(Math.random() * 1000) + 1;
  const JsonData = { id, ...reqBody };
  console.log(JsonData);
  dataArray.push(JsonData);
  const updatedJsonData = JSON.stringify(dataArray);

  fs.writeFile(fileDB, updatedJsonData, "utf8", (error) => {
    if (error) {
      res.status(404).send("File not found.");
    }
    console.log("Data has been written to the file.");
    res.status(201).json({ id });
  });
});

app.get('/todos', (req, res) => {
  const existingData = fs.readFileSync(fileDB, "utf8");
  if (existingData !== "") {
    dataArray = JSON.parse(existingData);
    res.send(dataArray)
  }
  else {
    res.status(404).send("No Todos")
  }
})

app.get('/todo/:id', (req, res) => {
  const id = parseInt(req.params.id)
  const existingData = fs.readFileSync(fileDB, "utf8");
  if (existingData !== "") {
    dataArray = JSON.parse(existingData);
    IdFound = dataArray.find(obj => obj.id === id)
    if (IdFound) {
      res.send(IdFound)
    }
    else {
      res.status(404).send('No matching id found')
    }
  }
  else {
    res.status(404).send("No Todos")
  }
})

app.put('/todo/:id', (req, res) => {
  const id = parseInt(req.params.id)
  const existingData = fs.readFileSync(fileDB, "utf8");
  if (existingData !== "") {
    dataArray = JSON.parse(existingData);
    IdFound = dataArray.find(obj => obj.id === id)
    if (IdFound) {
      const { title, description, completed } = req.body
      IdFound.title = title
      IdFound.description = description
      IdFound.completed = completed

      const updatedData = JSON.stringify(dataArray);
      fs.writeFile(fileDB, updatedData, "utf8", (error) => {
        if (error) {
          res.status(404).send("File not found.");
        }
        console.log("Data has been written to the file.");
        res.send(`Updated the ID - ${id}`);
      });
    }
    else {
      res.status(404).send('No matching id found')
    }
  }
  else {
    res.status(404).send("No Todos")
  }
})


app.delete('/todo/:id', (req, res) => {
  const id = parseInt(req.params.id)
  const existingData = fs.readFileSync(fileDB, "utf8");
  if (existingData !== "") {
    dataArray = JSON.parse(existingData);
    IdFound = dataArray.find(obj => obj.id === id)
    if (IdFound) {
      const updatedArray = dataArray.filter(obj => obj.id !== id);
      const updatedData = JSON.stringify(updatedArray);
      fs.writeFile(fileDB, updatedData, "utf8", (error) => {
        if (error) {
          res.status(404).send("File not found.");
        }
        console.log("Data has been written to the file.");
        res.send(`Deleted the ID - ${id}`);
      });
    }
    else {
      res.status(404).send('No matching id found')
    }
  }
  else {
    res.status(404).send("No Todos")
  }
})

app.use((req, res) => {
  res.status(404).send("404 Not Found");
});


module.exports = app;
